### ISSUE TITLE
Integration error, no new updates since v2025.1.x

### ISSUE THREAD

**Issue by mbu147** [VarChar42/hassio-netzooe-eservice#5]
Hi @VarChar42 ,

since I updated to v2025.1.x last week the integration reports the following error:

```
  File "/config/custom_components/netzooe_eservice/sensor.py", line 22, in <module>
    from homeassistant.const import ENERGY_KILO_WATT_HOUR
ImportError: cannot import name 'ENERGY_KILO_WATT_HOUR' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py)
```
I could solve this on my end by replacing ENERGY_KILO_WATT_HOUR with UnitOfEnergy.KILO_WATT_HOUR in sensor.py.

I created a PR for this, please take a look into it :)
#4

**Comment by mbu147** [comment]
You're welcome. Can you create a new release with the bugfix?

**Comment by VarChar42** [comment]
Done. Just made sure it also works on my instance :)
